[phases.setup]
nixPkgs = [
  "python3",
  "unzip",
  "bun",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "mesa",
  "libxkbcommon",
  "gtk3",
  "pango",
  "cairo",
  "glib",
  "dbus",
  "expat",
  "libdrm",
  "alsa-lib",
  "cups",
]

# Removemos a sobrescrita do [phases.install].
# Assim, o Railway cuida sozinho de baixar o Python, configurar o venv e rodar o `pip install -r requirements.txt`.

[phases.build]
cmds = [
  "playwright install chromium --with-deps",
  "reflex export --frontend-only --no-zip"
]

[start]
cmd = "reflex db migrate && reflex run --env prod --backend-port $PORT"
