[phases.setup]
nixPkgs = [
  "unzip",
  "bun",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "mesa",
  "libxkbcommon",
  "gtk3",
  "pango",
  "cairo",
  "glib",
  "dbus",
  "expat",
  "libdrm",
  "alsa-lib",
  "cups",
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium --with-deps",
]

[phases.build]
cmds = ["reflex export --frontend-only --no-zip"]

[start]
cmd = "reflex db migrate && reflex run --env prod --backend-only"
