"""empty message

Revision ID: 405305974e72
Revises: 
Create Date: 2026-06-10 13:50:10.791836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '405305974e72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfilacademico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ra', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dados_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfilacademico')
    # ### end Alembic commands ###
