"""add_senha

Revision ID: cdbe8c4e7091
Revises: 405305974e72
Create Date: 2026-06-10 14:01:17.020401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cdbe8c4e7091'
down_revision: Union[str, Sequence[str], None] = '405305974e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfilacademico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_criptografada', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfilacademico', schema=None) as batch_op:
        batch_op.drop_column('senha_criptografada')

    # ### end Alembic commands ###
